#!/bin/sh
# pre-commit hook to run golangci-lint

# Exit immediately if a command exits with a non-zero status
set -e

# Run golangci-lint on staged files
echo "Running golangci-lint..."
STAGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR -- '*.go' | grep -v '^vendor/' || true)

if [ -n "$STAGED_FILES" ]; then
    echo "$STAGED_FILES" | xargs golangci-lint run
	echo "golangci-lint passed successfully."

	echo "Formatting staged files with golangci-lint fmt..."
    echo "$STAGED_FILES" | xargs golangci-lint fmt

    echo "$STAGED_FILES" | xargs git add
    echo "Formatted files have been added back to the staging area."
else
    echo "No staged Go files to format."
fi

exit 0
